services:
  postgres-db:
    image: postgres:15
    container_name: url_shortener_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: urldb
    ports:
      - "5432:5432"